version: "3"
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    expose:
      - "3000"
    command: ["./wait-for-it.sh", "database:5432", "--", "yarn", "start:server"]
    environment:
      DATABASE_HOST: database
      DATABASE_PORT: 5432
    depends_on:
      - database
    restart: unless-stopped

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["sh", "-c", "./wait-for-it.sh database:5432 -- ./wait-for-it.sh server:3000 -- yarn start:worker"]
    environment:
      DATABASE_HOST: database
      DATABASE_PORT: 5432
    depends_on:
      - server
    restart: unless-stopped

  storefront:
    build:
      context: .
      dockerfile: Dockerfile-storefront
      args:
        STOREFRONT_VERSION: 0.3.1
    ports:
      - 4000:4000
    expose:
      - "4000"
    environment:
      SERVER_API_HOST: http://server
      SERVER_API_PORT: 3000
      SERVER_API_PATH: shop-api
    depends_on:
      - server
    restart: unless-stopped

  database:
    image: postgres:17
    volumes:
      - /var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: vendure
    restart: unless-stopped
